"""Provenance footer for rendered census maps.

A small self-contained (inline-styled) HTML box crediting the Facetwork workflow
that produced a map and linking to its FFL source on GitHub — so anyone viewing
a published page can trace it back to the workflow definition that built it.
Mirrors the save-earth map footer; kept inline-styled so it drops cleanly into
each renderer's own ``<style>`` without collisions.
"""

from __future__ import annotations

from datetime import UTC, datetime
from html import escape


def _now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

# The census workflows all live in one FFL file on GitHub.
CENSUS_FFL_URL = "https://github.com/rlemke/fwh_census_us/blob/main/src/census_us/ffl/census.ffl"


def footer_html(workflow: str, ffl_url: str = CENSUS_FFL_URL, params: dict | None = None) -> str:
    """Return an inline-styled provenance footer ``<div>`` for ``workflow``.

    ``params`` (the workflow inputs that produced this page) are shown as a
    call — e.g. ``BuildStateMetricsMap(state_fips=48, state_name=Texas)`` — so
    the page records exactly how to regenerate it.
    """
    call = workflow
    if params:
        kv = ", ".join(f"{k}={v}" for k, v in params.items() if v not in (None, ""))
        if kv:
            call = f"{workflow}({kv})"
    repo_url = ffl_url.split("/blob/")[0] if "/blob/" in ffl_url else ffl_url
    return (
        '<div style="position:fixed;bottom:10px;left:10px;z-index:9999;'
        "background:rgba(255,255,255,0.92);border-radius:6px;padding:6px 10px;"
        "box-shadow:0 1px 4px rgba(0,0,0,0.2);font:11px system-ui,sans-serif;"
        'color:#444;max-width:440px">'
        "Generated by Facetwork workflow "
        f'<code style="background:#f0f0f0;padding:0 3px;border-radius:3px">{escape(call)}</code>'
        f' &middot; <a href="{escape(ffl_url)}" target="_blank" rel="noopener" '
        'style="color:#1565c0;text-decoration:none">view FFL</a>'
        f' &middot; <a href="{escape(repo_url)}" target="_blank" rel="noopener" '
        'style="color:#1565c0;text-decoration:none">source repo</a>'
        f" &middot; generated {_now()}</div>"
    )
